import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],

  openApiSidebar: [
    {
      type: "category",
      label: "Petstore (Example)",
      link: {
        type: "generated-index",
        title: "Petstore API (Example)",
        description:
          "This is an example set of API docs from Swagger's Petstore example.",
        slug: "/api/petstore-api"
      },
      items: require("./docs/api/petstore/sidebar.js")
    }
  ]
};

export default sidebars;
